pull_request_rules:
  - name: automatic merge from Dependabot
    conditions:
      - author=dependabot[bot]
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
        strict: true
